Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 5
Edges:
 0: 0-1
 1: 1-3 1-4
 2: 2-1 2-3
 3:
 4:

Enter the source vertex: Reachable from vertex 0:
0
1
2
3
4
Enter the source vertex: Reachable from vertex 1:
0
1
2
3
4
Enter the source vertex: Reachable from vertex 2:
0
1
2
3
4
Enter the source vertex: Reachable from vertex 3:
3
Enter the source vertex: Reachable from vertex 4:
4
Enter the source vertex: 