Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 6
Edges:
 0: 0-1
 1:
 2: 2-1 2-3 2-5
 3: 3-4
 4:
 5:

Enter the source vertex: Reachable from vertex 0:
0
1
2
3
5
Enter the source vertex: Reachable from vertex 1:
1
Enter the source vertex: Reachable from vertex 2:
0
1
2
3
5
Enter the source vertex: Reachable from vertex 3:
3
4
Enter the source vertex: Reachable from vertex 4:
4
Enter the source vertex: Reachable from vertex 5:
5
Enter the source vertex: 